@startuml

package "validate" {
	class "ErrAgeOutOfRange" as validate.ErrAgeOutOfRange <<V,Orchid>> {
		+Age: int
		+Error(): string
	}
}



package "validate" {
	class "ErrCountry" as validate.ErrCountry <<V,Orchid>> {
		+Country: string
		+Error(): string
	}
}



package "validate" {
	class "ErrDOB" as validate.ErrDOB <<V,Orchid>> {
		+DOB: string
		+Error(): string
	}
}



package "validate" {
	class "ErrEmail" as validate.ErrEmail <<V,Orchid>> {
		+Email: string
		+Error(): string
	}
}



package "validate" {
	class "ErrGender" as validate.ErrGender <<V,Orchid>> {
		+Gender: string
		+Error(): string
	}
}



package "validate" {
	class "ErrPhoneNumber" as validate.ErrPhoneNumber <<V,Orchid>> {
		+PhoneNumber: string
		+Error(): string
	}
}



package "validate" {
	class "ErrPhoneType" as validate.ErrPhoneType <<V,Orchid>> {
		+Type: string
		+Error(): string
	}
}



package "validate" {
	class "ErrPreferenceFlag" as validate.ErrPreferenceFlag <<V,Orchid>> {
		+Flag: string
		+Error(): string
	}
}



package "validate" {
	class "ErrUserID" as validate.ErrUserID <<V,Orchid>> {
		+UserID: string
		+Error(): string
	}
}



package "validate" {
	class "ErrZIP" as validate.ErrZIP <<V,Orchid>> {
		+Country: string
		+ZIP: string
		+Error(): string
	}
}



package "user" {
	class "AcvLog" as user.AcvLog <<E,#FFCC00>> {
		+RwsID: int
		+Now: func() time.Time
		+Hostname: string
		+Records: acvlog.Records
		+LogExternalIDs(uID: string, pID: int32, m: map[string][]string)
		+LogInsertPlayerActivity(flags: uint, uID: string, pID: int32, new: *user.Player)
		+LogPlayerActivity(flags: uint, uID: string, pID: int32, old: *user.Player, new: *user.Player)
		+LogInsertKsUserActivity(uID: string, pID: int32, new: *user.KSUser)
		+LogKsUserActivity(uID: string, pID: int32, old: *user.KSUser, new: *user.KSUser)
		+LogOrgUserDataActivity(uID: string, pID: int32, reqKey: string, data: map[string]user.Value)
		+LogDeletePhoneNumber(uID: string, pID: int64, ppnID: int32)
		+LogPhoneNumberActivity(uID: string, pID: int32, pn: *user.phoneNumber, ppn: *user.playerPhoneNumber, isNew: bool)
		+LogJSONField(uID: string, pID: int32, tag: string, v: user.Identifier, isDelete: bool)
		+LogExpiringUserTag(uID: string, pID: int32, tag: string, expires: string)
		-addChangesToLogs(uID: string, pID: int32, s: acvlog.Source, changes: diff.Diff)
		-addNewUserActivity(uID: string, pID: int32, s: acvlog.Source, field: string, old: string, new: string)
		-getTime(): time.Time
	}
}


	user.AcvLog ..> user.Player : <<use>> 
	user.AcvLog ..> user.Player : <<use>> 
	user.AcvLog ..> user.Player : <<use>> 
	user.AcvLog ..> user.KSUser : <<use>> 
	user.AcvLog ..> user.KSUser : <<use>> 
	user.AcvLog ..> user.KSUser : <<use>> 
	user.AcvLog ..> user.Value : <<use>> 
	user.AcvLog ..> user.phoneNumber : <<use>> 
	user.AcvLog ..> user.playerPhoneNumber : <<use>> 
	user.AcvLog ..> user.Identifier : <<use>> 

package "user" {
	class "AddBasicFunc" as user.AddBasicFunc <<V,Orchid>> {
		+AddBasicFunc(ctx: context.Context, extID: string): (userID: string, playerID: int32, err: error)
	}
}


	user.AddBasicFunc ..> error : <<return>> 

package "user" {
	class "AppendedData" as user.AppendedData <<E,#FFCC00>> {
		+AddVar(orgModel: string, key: string, val: user.Data)
		+UnmarshalJSON(data: []byte): error
	}
}


	user.AppendedData ..> user.Data : <<use>> 
	user.AppendedData ..> error : <<return>> 

package "user" {
	class "AttributeType" as user.AttributeType <<E,#FFCC00>> {
		+Scan(v: interface{}): error
		+Value(): (driver.Value, error)
	}
}


	user.AttributeType ..> error : <<return>> 
	user.AttributeType ..> error : <<return>> 

package "user" {
	class "BoolField" as user.BoolField <<E,#FFCC00>> {
		+NullBool: sql.NullBool
		+Present: bool
		+UnmarshalJSON(data: []byte): error
		+UnmarshalCSV(data: []byte): error
	}
}


	user.BoolField ..> error : <<return>> 
	user.BoolField ..> error : <<return>> 

package "user" {
	interface "Data" as user.Data
}



package "user" {
	class "Date" as user.Date <<V,Orchid>> {
		+DateTime: user.DateTime
		+MarshalBinary(): ([]byte, error)
		+MarshalJSON(): ([]byte, error)
	}
}

	user.Date --> user.DateTime

	user.Date ..> error : <<return>> 
	user.Date ..> error : <<return>> 

package "user" {
	class "DateTime" as user.DateTime <<V,Orchid>> {
		+Time: time.Time
		+MarshalJSON(): ([]byte, error)
		+MarshalText(): ([]byte, error)
		+MarshalBinary(): ([]byte, error)
		+String(): string
		+Value(): (driver.Value, error)
	}
}


	user.DateTime ..> error : <<return>> 
	user.DateTime ..> error : <<return>> 
	user.DateTime ..> error : <<return>> 
	user.DateTime ..> error : <<return>> 

package "user" {
	class "EmailLookupRequiredError" as user.EmailLookupRequiredError <<V,Orchid>> {
		+Error(): string
	}
}



package "user" {
	class "ErrDoesNotExist" as user.ErrDoesNotExist <<V,Orchid>> {
		+Method: string
		+Key: string
		+Error(): string
	}
}



package "user" {
	class "ErrUnknownAttr" as user.ErrUnknownAttr <<V,Orchid>> {
		+Attr: string
		+Error(): string
	}
}



package "user" {
	class "ExclusionErr" as user.ExclusionErr <<V,Orchid>> {
		+Value: user.Value
		+ExcludedValues: []interface{}
		+Error(): string
	}
}

	user.ExclusionErr --> user.Value


package "user" {
	class "FilterRule" as user.FilterRule <<V,Orchid>>
}



package "user" {
	class "FilterRules" as user.FilterRules <<E,#FFCC00>> {
		+Scan(v: interface{}): error
		+Value(): (driver.Value, error)
	}
}


	user.FilterRules ..> error : <<return>> 
	user.FilterRules ..> error : <<return>> 
user.FilterRules *-- user.FilterRule
package "user" {
	interface "Identifier" as user.Identifier {
		+PrimaryKey(): string
	}
}



package "user" {
	class "InclusionErr" as user.InclusionErr <<V,Orchid>> {
		+Value: user.Value
		+ExpectedValues: []interface{}
		+Error(): string
	}
}

	user.InclusionErr --> user.Value


package "user" {
	class "InconsistentEmailsError" as user.InconsistentEmailsError <<V,Orchid>> {
		+Error(): string
	}
}



package "user" {
	class "IntField" as user.IntField <<E,#FFCC00>> {
		+NullInt64: sql.NullInt64
		+Present: bool
		+UnmarshalJSON(data: []byte): error
		+UnmarshalCSV(data: []byte): error
	}
}


	user.IntField ..> error : <<return>> 
	user.IntField ..> error : <<return>> 

package "user" {
	class "InvalidJSONListErr" as user.InvalidJSONListErr <<V,Orchid>> {
		+Type: string
		+Data: string
		+Error(): string
	}
}



package "user" {
	class "InvalidTypeErr" as user.InvalidTypeErr <<V,Orchid>> {
		+Type: user.AttributeType
		+List: bool
		+Value: user.Value
		+Error(): string
	}
}

	user.InvalidTypeErr --> user.AttributeType
	user.InvalidTypeErr --> user.Value


package "user" {
	class "KSTime" as user.KSTime <<V,Orchid>> {
		+Time: invalid type
		+Change(): (string, error)
		+IsZero(): bool
	}
}


	user.KSTime ..> error : <<return>> 

package "user" {
	class "KSUser" as user.KSUser <<E,#FFCC00>> {
		+Model: invalid type
		+PlayerID: int32
		+DOB: invalid type
		+Gender: invalid type
		+ZIP: invalid type
		+HomeZIP: invalid type
		+DMA: invalid type
		+HomeDMA: invalid type
		+Country: invalid type
		+HomeCountry: invalid type
		+State: invalid type
		+HomeState: invalid type
		+HomeCity: invalid type
		+Ethnicity: invalid type
		+HHI: invalid type
		+Locale: invalid type
		+Parent: invalid type
		+HomeAddressEncrypted: enc.NullEncryptedString
		+HomeAddress2Encrypted: enc.NullEncryptedString
		+OptedOut: bool
		+AppExperiments: invalid type
		+CachedAvailablePoints: invalid type
		+CreatedAt: user.KSTime
		+DeviceIDs: invalid type
		+HasNotSeenAchievements: invalid type
		+LastSeenAt: invalid type
		+LastSessionStartedAt: invalid type
		+LastUserSessionIDs: invalid type
		+PlayerDataCenterID: invalid type
		+SchemaVersion: invalid type
		+UpdatedAt: user.KSTime
		+SourceApplicationID: int
		+PrimaryExternalID: invalid type
		-setDefaults(appID: int)
	}
}

	user.KSUser --> user.KSTime
	user.KSUser --> user.KSTime


package "user" {
	class "KsUserKey" as user.KsUserKey <<V,Orchid>> {
		+RwsID: int32
		+UserID: string
		+Args(cf: string): []interface{}
		+String(): string
	}
}



package "user" {
	class "Legacy" as user.Legacy <<V,Orchid>> {
		-logpub: acvlog.Publisher
		+Publish(ctx: context.Context, recs: acvlog.Records): error
		+Close(): error
	}
}


	user.Legacy ..> error : <<return>> 
	user.Legacy ..> error : <<return>> 

package "user" {
	class "Length" as user.Length <<E,#FFCC00>> {
		+Max: *int
		+Min: *int
		+Is: *int
		+Scan(v: interface{}): error
		+Value(): (driver.Value, error)
		-validateString(s: string): error
	}
}


	user.Length ..> error : <<return>> 
	user.Length ..> error : <<return>> 

package "user" {
	class "LengthErr" as user.LengthErr <<V,Orchid>> {
		+Value: string
		+Rule: string
		+RuleValue: int
		+Error(): string
	}
}



package "user" {
	class "Loader" as user.Loader <<E,#FFCC00>> {
		-db: sqlxcontext.DB
		-corm: *invalid type
		-logpub: acvlog.Publisher
		-encKey: []byte
		-appID: int
		-orgID: int
		-rewardsID: int
		-devID: int
		-dataCenterID: int
		-attrMap: map[string][]user.OrganizationModelAttribute
		-ip: string
		-now: func() time.Time
		+SaveEmptyUserProfile: bool
		+UserAutoCreate: bool
		+UnlinkExternalIDs: bool
		+ColumnFamilyMigration: bool
		+PlayerDOYLoggingEnabled: bool
		+SkipXIDConsistencyValidation: bool
		+CreateOrUpdateUser(c: context.Context, h: lookup.Header, u: *user.User): err: error
		-newKSPlayerID(): *user.ksPlayerInfo
		+LogAppendedData(c: context.Context, h: lookup.Header, u: *user.User): error
		-logAppendedData(c: context.Context, h: lookup.Header, u: *user.User, avl: *user.AcvLog): error
		+UpdateOrCreateUnlinkedUser(c: context.Context, h: lookup.Header, u: *user.User): err: error
		+CreateUser(c: context.Context, _: lookup.Header, u: *user.User): err: error
		+AddBasicUser(c: context.Context, extID: string): (userID: string, playerID: int32, err: error)
		+UpdateUser(c: context.Context, h: lookup.Header, u: *user.User): err: error
		+UpdateUserWithAppendedData(c: context.Context, playerID: int, extID: string, reqKey: string, in: map[string]user.Value, cur: map[string]user.Value): error
		-updateUserWithAppendedData(c: context.Context, db: user.dber, p: *user.Player, extID: string, reqKey: string, in: map[string]user.Value, cur: map[string]user.Value, avl: *user.AcvLog): err: error
		-newAppendedData(): user.AppendedData
		-validateRequestDataConsistency(db: user.dber, lookupTyp: string, u: *user.User): error
		-validAppendedData(ad: user.AppendedData): error
		-insert(c: context.Context, db: user.dber, lookupTyp: string, u: *user.User, avl: *user.AcvLog): (userKey: *user.KsUserKey, playerID: int32, err: error)
		-insertPrimaryOrgUser(db: user.dber, u: *user.User, userID: string, playerID: int64, avl: *user.AcvLog): error
		-insertAppendedData(c: context.Context, db: user.dber, u: *user.User, p: *user.Player, userID: string, pID: int32, avl: *user.AcvLog): error
		-update(c: context.Context, db: user.dber, lookupTyp: string, u: *user.User, p: *user.Player, avl: *user.AcvLog): err: error
		-updatePrimaryOrgUser(c: context.Context, db: user.dber, u: *user.User, userID: string, playerID: int64, avl: *user.AcvLog): error
		-playerByLookupKey(db: user.dber, key: string, u: *user.User): (p: user.Player, err: error)
		-playerByExtID(db: user.dber, u: *user.User): (p: user.Player, err: error)
		-playerByEmail(db: user.dber, u: *user.User): (p: user.Player, err: error)
		-playerByID(db: user.dber, playerID: int32): (*user.Player, error)
		-playerByUserID(db: user.dber, userID: string): (p: user.Player, err: error)
		-updateKsUser(ksUser: *user.KSUser, u: *user.User, now: time.Time, encKey: []byte)
		-isUnknownYearUpdate(old: string, new: string): bool
		-updatedPlayer(u: *user.User, now: time.Time, p: *user.Player, encKey: []byte): *user.Player
		-newPlayer(u: *user.User, now: time.Time, userID: string, encKey: []byte, aID: int): *user.Player
		-getLogFlags(): uint
		-newPhoneNumber(number: string, encKey: []byte): *user.phoneNumber
		-newPlayerPhoneNumber(pID: int64, pnID: int64, pn: *user.PhoneNumber): *user.playerPhoneNumber
		-insertPlayerPhoneNumbers(db: user.dber, orgID: int64, pID: int64, phoneNumbers: []user.PhoneNumber, userID: string, avl: *user.AcvLog): error
		-updatePlayerPhoneNumbers(db: user.dber, orgID: int64, pID: int64, pns: user.PhoneNumbersField, userID: string, avl: *user.AcvLog): error
		-existingPhoneNumbers(db: user.dber, pID: int64): (map[string]int32, error)
		-split(db: user.dber, numbers: []user.PhoneNumber, pID: int64): ([]user.PhoneNumber, []int32, error)
		-unlinkPlayers(c: context.Context, db: user.dber, u: *user.User): error
		-newUnlinkedUser(u: *user.User, encKey: []byte, orgID: int): *user.unlinkedUser
		-insertUnlinkedUser(db: user.dber, u: *user.User): error
		-newUnlinkedUserData(u: *user.User, t: user.Type, orgID: int): (*user.unlinkedUserData, error)
		-insertUserData(db: user.dber, u: *user.User): error
		-insertUserProfileData(db: user.dber, u: *user.User): error
	}
}

	user.Loader --> user.OrganizationModelAttribute

	user.Loader ..> user.User : <<use>> 
	user.Loader ..> error : <<return>> 
	user.Loader ..> user.User : <<use>> 
	user.Loader ..> error : <<return>> 
	user.Loader ..> user.User : <<use>> 
	user.Loader ..> error : <<return>> 
	user.Loader ..> user.User : <<use>> 
	user.Loader ..> error : <<return>> 
	user.Loader ..> error : <<return>> 
	user.Loader ..> user.User : <<use>> 
	user.Loader ..> error : <<return>> 
	user.Loader ..> user.Value : <<use>> 
	user.Loader ..> user.Value : <<use>> 
	user.Loader ..> error : <<return>> 

package "user" {
	class "NullTime" as user.NullTime <<V,Orchid>> {
		+NullTime: mysql.NullTime
		+Change(): (string, error)
		+IsZero(): bool
	}
}


	user.NullTime ..> error : <<return>> 

package "user" {
	class "Number" as user.Number <<E,#FFCC00>> {
		-valid: bool
		-number: json.Number
		-cachedInt: sql.NullInt64
		-cachedFloat: sql.NullFloat64
		+Valid(): bool
		+Int64(): (int64, error)
		+String(): string
		+Float64(): (float64, error)
		+MarshalYAML(): (interface{}, error)
		+UnmarshalYAML(unmarshal: func(interface{}) error): error
	}
}


	user.Number ..> error : <<return>> 
	user.Number ..> error : <<return>> 
	user.Number ..> error : <<return>> 
	user.Number ..> error : <<return>> 

package "user" {
	class "Numericality" as user.Numericality <<E,#FFCC00>> {
		+GreaterThan: *user.Number
		+GreaterThanOrEqual: *user.Number
		+LessThan: *user.Number
		+LessThanOrEqual: *user.Number
		+Even: bool
		+Odd: bool
		+IntegerOnly: bool
		+List: bool
		+Scan(v: interface{}): error
		+Value(): (driver.Value, error)
		-validateInt64Number(rule: string, number: *user.Number, val: int64, ruleFn: func(ruleValue int64, val int64) bool): error
		-validateInt64(i: int64): error
		-validateFloat64Number(rule: string, number: *user.Number, val: float64, ruleFn: func(ruleValue float64, val float64) bool): error
		-validateFloat64(f: float64): error
	}
}

	user.Numericality --> user.Number
	user.Numericality --> user.Number
	user.Numericality --> user.Number
	user.Numericality --> user.Number

	user.Numericality ..> error : <<return>> 
	user.Numericality ..> error : <<return>> 

package "user" {
	class "NumericalityErr" as user.NumericalityErr <<V,Orchid>> {
		+Rule: string
		+RuleValue: user.Value
		+Value: user.Value
		+Error(): string
	}
}

	user.NumericalityErr --> user.Value
	user.NumericalityErr --> user.Value


package "user" {
	class "OrgUser" as user.OrgUser <<V,Orchid>> {
		+ID: int32
		+OrgID: null.Int
		+ExternalID: null.String
		+PlayerID: null.Int
		+ExternalIDType: null.String
		+PrimaryKey(): string
	}
}



package "user" {
	class "OrganizationModelAttribute" as user.OrganizationModelAttribute <<E,#FFCC00>> {
		+ID: int32
		+OrganizationModelID: sql.NullInt64
		+Name: sql.NullString
		+DisplayName: sql.NullString
		+AttributeType: user.AttributeType
		+Filters: user.FilterRules
		+Caseinsensitive: sql.NullBool
		+Inclusion: enc.YAMLArray
		+Exclusion: enc.YAMLArray
		+Format: sql.NullString
		+Length: *user.Length
		+Numericality: *user.Numericality
		+DataOrganizationModelID: sql.NullInt64
		+IsList: sql.NullBool
		+ComplexAttributes: []user.OrganizationModelAttribute
		+ParseData(d: user.Data): (user.Value, error)
		-parseText(t: user.Text): (user.Value, error)
		-parseListText(t: user.Text): (user.Value, error)
		-parseList(vs: []interface{}): (user.Value, error)
		-validationError(v: interface{}, err: error): error
		-validateString(s: string): error
		-validateInt64(n: int64): error
		-validateFloat64(f: float64): error
		-validateComplex(m: map[string]interface{}): (map[string]user.Value, error)
		-handleValue(v: interface{}): (user.Value, error)
	}
}

	user.OrganizationModelAttribute --> user.AttributeType
	user.OrganizationModelAttribute --> user.FilterRules
	user.OrganizationModelAttribute --> user.Length
	user.OrganizationModelAttribute --> user.Numericality
	user.OrganizationModelAttribute --> user.OrganizationModelAttribute

	user.OrganizationModelAttribute ..> user.Data : <<use>> 
	user.OrganizationModelAttribute ..> user.Value : <<return>> 
	user.OrganizationModelAttribute ..> error : <<return>> 

package "user" {
	class "PhoneDeactivator" as user.PhoneDeactivator <<E,#FFCC00>> {
		-db: sqlxcontext.DB
		-logpub: acvlog.Publisher
		-cl: client.Client
		-encKey: []byte
		-rwsID: int
		+Deactivate(numbers: []string): (n: int, err: error)
		-deactivate(id: int): err: error
		-existingNumbers(numbers: []string): (ids: []int, err: error)
	}
}


	user.PhoneDeactivator ..> error : <<return>> 

package "user" {
	class "PhoneNumber" as user.PhoneNumber <<V,Orchid>> {
		+PhoneNumber: string
		+PhoneType: string
		+PreferenceFlags: []string
		+VerifiedOwnership: bool
		-valid(): error
	}
}



package "user" {
	class "PhoneNumbersField" as user.PhoneNumbersField <<E,#FFCC00>> {
		+PhoneNumbers: []user.PhoneNumber
		+Present: bool
		+UnmarshalCSV(data: []byte): error
		+UnmarshalJSON(data: []byte): error
	}
}

	user.PhoneNumbersField --> user.PhoneNumber

	user.PhoneNumbersField ..> error : <<return>> 
	user.PhoneNumbersField ..> error : <<return>> 

package "user" {
	class "Player" as user.Player <<V,Orchid>> {
		+ID: int32
		+ExternalID: sql.NullString
		+Email: enc.EncryptedUniqueString
		+UserID: sql.NullString
		+DOB: enc.NullEncryptedUniqueString
		+YOB: sql.NullInt64
		+FirstName: sql.NullString
		+LastName: sql.NullString
		+Gender: sql.NullString
		+ZIP: sql.NullString
		+HHI: sql.NullString
		+Ethnicity: sql.NullString
		+ParentalStatus: sql.NullString
		+RegisteredApplicationID: sql.NullInt64
		+DataCenterID: sql.NullInt64
		+AccountStatus: sql.NullString
		+IPAddress: sql.NullString
		+RewardsSystemID: sql.NullInt64
		+DMA: sql.NullString
		+Country: sql.NullString
		+OptedOut: sql.NullBool
		+CreatedAt: user.NullTime
		+UpdatedAt: user.NullTime
	}
}

	user.Player --> user.NullTime
	user.Player --> user.NullTime


package "user" {
	interface "Selecter" as user.Selecter {
		+Select(dest: interface{}, query: string, args: []interface{}): error
	}
}


	user.Selecter ..> error : <<return>> 

package "user" {
	class "Status" as user.Status <<E,#FFCC00>> {
		+Scan(src: interface{}): error
		+Value(): (driver.Value, error)
	}
}


	user.Status ..> error : <<return>> 
	user.Status ..> error : <<return>> 

package "user" {
	class "StringField" as user.StringField <<E,#FFCC00>> {
		+NullString: sql.NullString
		+Present: bool
		+UnmarshalJSON(data: []byte): error
		+UnmarshalCSV(data: []byte): error
	}
}


	user.StringField ..> error : <<return>> 
	user.StringField ..> error : <<return>> 

package "user" {
	class "Text" as user.Text <<V,Orchid>>
}



package "user" {
	class "Type" as user.Type <<E,#FFCC00>> {
		+Scan(src: interface{}): error
		+Value(): (driver.Value, error)
	}
}


	user.Type ..> error : <<return>> 
	user.Type ..> error : <<return>> 

package "user" {
	class "UnsupportedFilterErr" as user.UnsupportedFilterErr <<V,Orchid>> {
		+Filter: user.FilterRule
		+Error(): string
	}
}

	user.UnsupportedFilterErr --> user.FilterRule


package "user" {
	class "User" as user.User <<V,Orchid>> {
		+Email: user.StringField
		+ExternalID: user.StringField
		+ProxyID: user.StringField
		+UserID: user.StringField
		+Gender: user.StringField
		+DOB: user.StringField
		+Country: user.StringField
		+State: user.StringField
		+City: user.StringField
		+ZIP: user.StringField
		+DMA: user.StringField
		+FirstName: user.StringField
		+LastName: user.StringField
		+HHI: user.StringField
		+Ethnicity: user.StringField
		+Locale: user.StringField
		+ParentalStatus: user.StringField
		+YOB: user.IntField
		+SMEffectiveDate: user.StringField
		+LinkIdentifier: user.StringField
		+Address: user.StringField
		+Address2: user.StringField
		+OptedOut: user.BoolField
		+AppendedData: user.AppendedData
		+ExternalIDs: map[string][]string
		+PhoneNumbers: user.PhoneNumbersField
		+Validate(h: lookup.Header): error
	}
}

	user.User --> user.StringField
	user.User --> user.StringField
	user.User --> user.StringField
	user.User --> user.StringField
	user.User --> user.StringField
	user.User --> user.StringField
	user.User --> user.StringField
	user.User --> user.StringField
	user.User --> user.StringField
	user.User --> user.StringField
	user.User --> user.StringField
	user.User --> user.StringField
	user.User --> user.StringField
	user.User --> user.StringField
	user.User --> user.StringField
	user.User --> user.StringField
	user.User --> user.StringField
	user.User --> user.IntField
	user.User --> user.StringField
	user.User --> user.StringField
	user.User --> user.StringField
	user.User --> user.StringField
	user.User --> user.BoolField
	user.User --> user.AppendedData
	user.User --> user.PhoneNumbersField

	user.User ..> error : <<return>> 

package "user" {
	class "ValidationErr" as user.ValidationErr <<V,Orchid>> {
		+Type: user.AttributeType
		+Attr: string
		+Value: user.Value
		+Err: error
		+Error(): string
	}
}

	user.ValidationErr --> user.AttributeType
	user.ValidationErr --> user.Value
	user.ValidationErr --> error


package "user" {
	interface "Value" as user.Value
}



package "user" {
	class "bufferedLogKey" as user.bufferedLogKey <<V,Orchid>>
}



package "user" {
	interface "dber" as user.dber {
		+Exec(query: string, args: []interface{}): (sql.Result, error)
		+Get(dest: interface{}, query: string, args: []interface{}): error
		+NamedExec(query: string, arg: interface{}): (sql.Result, error)
		+PrepareNamed(query: string): (sqlxcontext.NamedStmt, error)
		+Query(query: string, args: []interface{}): (sql.Rows, error)
		+Select(: interface{}, : string, : []interface{}): error
	}
}


	user.dber ..> error : <<return>> 
	user.dber ..> error : <<return>> 
	user.dber ..> error : <<return>> 
	user.dber ..> error : <<return>> 
	user.dber ..> error : <<return>> 
	user.dber ..> error : <<return>> 

package "user" {
	class "guardedLazyLogger" as user.guardedLazyLogger <<E,#FFCC00>> {
		+Mutex: sync.Mutex
		+Logger: activitylog.Logger
		+Log(entries: activitylog.Entry): error
		+LogReset()
		+SetLogOutput(w: io.Writer)
		+SetLogEncoding(e: activitylog.Encoder)
		+UseAppendOnlyLog(c: context.Context, cfgOption: bool): error
	}
}


	user.guardedLazyLogger ..> error : <<return>> 
	user.guardedLazyLogger ..> error : <<return>> 

package "user" {
	class "ksPlayerInfo" as user.ksPlayerInfo <<V,Orchid>> {
		+Model: invalid type
		+PlayerID: int32
	}
}



package "user" {
	class "phoneNumber" as user.phoneNumber <<V,Orchid>> {
		+ID: int32
		+PhoneNumber: enc.NullEncryptedUniqueString
		+OldPhoneNumber: enc.EncryptedUniqueString
		+CreatedAt: null.Time
		+UpdatedAt: null.Time
		+PhoneCarrierID: null.Int
	}
}



package "user" {
	class "playerPhoneNumber" as user.playerPhoneNumber <<V,Orchid>> {
		+ID: int32
		+PhoneNumberID: int32
		+PlayerID: int32
		+VerifiedOwnership: bool
		+PhoneType: null.String
		+PreferenceFlags: uint32
		+CreatedAt: null.Time
		+UpdatedAt: null.Time
	}
}



package "user" {
	class "skipAppendedDataKey" as user.skipAppendedDataKey <<V,Orchid>>
}



package "user" {
	class "unlinkedUser" as user.unlinkedUser <<V,Orchid>> {
		+ID: int32
		+OrganizationID: sql.NullInt64
		+ExternalID: sql.NullString
		+LinkIdentifierEncrypted: enc.NullEncryptedUniqueString
		+Code: sql.NullString
		+Status: user.Status
		+PlayerID: sql.NullInt64
		+UserID: sql.NullString
		+ImportedAt: mysql.NullTime
		+CreatedAt: mysql.NullTime
		+UpdatedAt: mysql.NullTime
	}
}

	user.unlinkedUser --> user.Status


package "user" {
	class "unlinkedUserData" as user.unlinkedUserData <<V,Orchid>> {
		+ID: int32
		+OrganizationID: sql.NullInt64
		+ExternalID: sql.NullString
		+Type: user.Type
		+DataEncrypted: enc.EncryptedString
	}
}

	user.unlinkedUserData --> user.Type


package "user" {
	class "userData" as user.userData <<V,Orchid>> {
		+User: *user.User
		+UserProfile: map[string]string
	}
}

	user.userData --> user.User


	validate.ErrAgeOutOfRange -up-|> user.Data
	validate.ErrAgeOutOfRange -up-|> user.Value
	validate.ErrCountry -up-|> user.Data
	validate.ErrCountry -up-|> user.Value
	validate.ErrDOB -up-|> user.Data
	validate.ErrDOB -up-|> user.Value
	validate.ErrEmail -up-|> user.Data
	validate.ErrEmail -up-|> user.Value
	validate.ErrGender -up-|> user.Data
	validate.ErrGender -up-|> user.Value
	validate.ErrPhoneNumber -up-|> user.Data
	validate.ErrPhoneNumber -up-|> user.Value
	validate.ErrPhoneType -up-|> user.Data
	validate.ErrPhoneType -up-|> user.Value
	validate.ErrPreferenceFlag -up-|> user.Data
	validate.ErrPreferenceFlag -up-|> user.Value
	validate.ErrUserID -up-|> user.Data
	validate.ErrUserID -up-|> user.Value
	validate.ErrZIP -up-|> user.Data
	validate.ErrZIP -up-|> user.Value
	user.AcvLog -up-|> user.Data
	user.AcvLog -up-|> user.Value
	user.AddBasicFunc -up-|> user.Data
	user.AddBasicFunc -up-|> user.Value
	user.AppendedData -up-|> user.Data
	user.AppendedData -up-|> user.Value
	user.AttributeType -up-|> user.Data
	user.AttributeType -up-|> user.Value
	user.BoolField -up-|> user.Data
	user.BoolField -up-|> user.Value
	user.Data -up-|> user.Value
	user.Date -up-|> user.Data
	user.Date -up-|> user.Value
	user.DateTime -up-|> user.Data
	user.DateTime -up-|> user.Value
	user.EmailLookupRequiredError -up-|> user.Data
	user.EmailLookupRequiredError -up-|> user.Value
	user.ErrDoesNotExist -up-|> user.Data
	user.ErrDoesNotExist -up-|> user.Value
	user.ErrUnknownAttr -up-|> user.Data
	user.ErrUnknownAttr -up-|> user.Value
	user.ExclusionErr -up-|> user.Data
	user.ExclusionErr -up-|> user.Value
	user.FilterRule -up-|> user.Data
	user.FilterRule -up-|> user.Value
	user.FilterRules -up-|> user.Data
	user.FilterRules -up-|> user.Value
	user.Identifier -up-|> user.Data
	user.Identifier -up-|> user.Value
	user.InclusionErr -up-|> user.Data
	user.InclusionErr -up-|> user.Value
	user.InconsistentEmailsError -up-|> user.Data
	user.InconsistentEmailsError -up-|> user.Value
	user.IntField -up-|> user.Data
	user.IntField -up-|> user.Value
	user.InvalidJSONListErr -up-|> user.Data
	user.InvalidJSONListErr -up-|> user.Value
	user.InvalidTypeErr -up-|> user.Data
	user.InvalidTypeErr -up-|> user.Value
	user.KSTime -up-|> user.Data
	user.KSTime -up-|> user.Value
	user.KSUser -up-|> user.Data
	user.KSUser -up-|> user.Value
	user.KsUserKey -up-|> user.Data
	user.KsUserKey -up-|> user.Value
	user.Legacy -up-|> user.Data
	user.Legacy -up-|> user.Value
	user.Length -up-|> user.Data
	user.Length -up-|> user.Value
	user.LengthErr -up-|> user.Data
	user.LengthErr -up-|> user.Value
	user.Loader -up-|> user.Data
	user.Loader -up-|> user.Value
	user.NullTime -up-|> user.Data
	user.NullTime -up-|> user.Value
	user.Number -up-|> user.Data
	user.Number -up-|> user.Value
	user.Numericality -up-|> user.Data
	user.Numericality -up-|> user.Value
	user.NumericalityErr -up-|> user.Data
	user.NumericalityErr -up-|> user.Value
	user.OrgUser -up-|> user.Data
	user.OrgUser -up-|> user.Identifier
	user.OrgUser -up-|> user.Value
	user.OrganizationModelAttribute -up-|> user.Data
	user.OrganizationModelAttribute -up-|> user.Value
	user.PhoneDeactivator -up-|> user.Data
	user.PhoneDeactivator -up-|> user.Value
	user.PhoneNumber -up-|> user.Data
	user.PhoneNumber -up-|> user.Value
	user.PhoneNumbersField -up-|> user.Data
	user.PhoneNumbersField -up-|> user.Value
	user.Player -up-|> user.Data
	user.Player -up-|> user.Value
	user.Selecter -up-|> user.Data
	user.Selecter -up-|> user.Value
	user.Status -up-|> user.Data
	user.Status -up-|> user.Value
	user.StringField -up-|> user.Data
	user.StringField -up-|> user.Value
	user.Text -up-|> user.Data
	user.Text -up-|> user.Value
	user.Type -up-|> user.Data
	user.Type -up-|> user.Value
	user.UnsupportedFilterErr -up-|> user.Data
	user.UnsupportedFilterErr -up-|> user.Value
	user.User -up-|> user.Data
	user.User -up-|> user.Value
	user.ValidationErr -up-|> user.Data
	user.ValidationErr -up-|> user.Value
	user.Value -up-|> user.Data
	user.bufferedLogKey -up-|> user.Data
	user.bufferedLogKey -up-|> user.Value
	user.dber -up-|> user.Data
	user.dber -up-|> user.Selecter
	user.dber -up-|> user.Value
	user.guardedLazyLogger -up-|> user.Data
	user.guardedLazyLogger -up-|> user.Value
	user.ksPlayerInfo -up-|> user.Data
	user.ksPlayerInfo -up-|> user.Value
	user.phoneNumber -up-|> user.Data
	user.phoneNumber -up-|> user.Value
	user.playerPhoneNumber -up-|> user.Data
	user.playerPhoneNumber -up-|> user.Value
	user.skipAppendedDataKey -up-|> user.Data
	user.skipAppendedDataKey -up-|> user.Value
	user.unlinkedUser -up-|> user.Data
	user.unlinkedUser -up-|> user.Value
	user.unlinkedUserData -up-|> user.Data
	user.unlinkedUserData -up-|> user.Value
	user.userData -up-|> user.Data
	user.userData -up-|> user.Value

@enduml
